---
# Node homogenity 
homogenity: False

# Network topoloy
topology: diamond

# Data files
edges_file: input_data/{topology}_edges.csv
nodes_file: input_data/{topology}_nodes.csv

# Options for drawing graph
graph_options: 
  arrows: True
  arrowstyle: ->
  node_size: 500
  node_color: pink
  width: 0.75  # edge line width
  edge_color: gray
  


