---
# Node homogenity 
homogenity: False

# Network topoloy
topology: diamond

# Data files
edges_file: input_data/{topology}_edges.csv
nodes_file: input_data/{topology}_nodes.csv

# Dawing options for graph
graph_options: 
  arrows: True
  arrowstyle: ->
  node_size: 500
  edgecolors: gray
  font_color: black
  width: 0.75 
  alpha: 0.75
  edge_color: gray

node_options:
  market:
    color: cyan
    label: market
  raw_material: 
    color: cyan
    label: raw material
  healthy:
    color: yellow
    label: null
  bankrupt:
    color: lightgray
    label: null
  
  

# Drawing options for adding edges
flow_options:
    order: 
      arrowstyle: simple
      edge_color: blue
    material:
      arrowstyle: simple
      alpha: 0.5
      edge_color: red
    cash:
      arrowstyle: simple
      edge_color: green


# Edge label options
flow_label_options:
  order:
    font_color: blue
  material:
    font_color: red
  cash:
    font_color: green




