---
# Node homogenity 
homogenity: False

# Network topoloy
topology: diamond

# Data files
edges_file: input_data/{topology}_edges.csv
nodes_file: input_data/{topology}_nodes.csv

# Dawing options for graph
graph_options: 
  arrows: True
  arrowstyle: ->
  node_size: 500
  edgecolors: gray
  font_color: black
  width: 0.75 
  alpha: 0.75
  edge_color: darkgray

node_options:
  market:
    color: green
    label: market
  other:
    color: yellow
    label: null
  raw_material: 
    color: green
    label: raw material
  

# Drawing options for adding edges
edge_options:
  arrowstyle: simple
  edge_color: blue


# Edge label options
edge_label_options:
  font_color: blue


