---
# Node homogenity 
homogenity: False

# Network topoloy
topology: diamond

# Data files
edges_file: input_data/{topology}_edges.csv
nodes_file: input_data/{topology}_nodes.csv

# Network drawing condfigurations
figsize: 
  x: 10
  y: 5

graph_options: 
  arrows: True
  arrowstyle: -|>
  node_size: 500
  edgecolors: lightgray
  font_color: black
  width: 1
  alpha: 0.75
  edge_color: lightgray

node_options:
  market:
    color: cyan
    label: market
  raw_material: 
    color: cyan
    label: raw material
  healthy:
    color: yellow
    label: null
  bankrupt:
    color: lightgray
    label: null
  
  
# Drawing options for adding edges
flow_options:
    order: 
      arrowstyle: simple
      edge_color: blue
      alpha: 0.75
    material:
      arrowstyle: simple
      alpha: 0.75
      edge_color: red
    cash:
      arrowstyle: simple
      edge_color: green
      alpha: 0.75


# Edge label options
flow_label_options:
  order:
    font_color: blue
  material:
    font_color: red
  cash:
    font_color: green





