---
# Simulation unique ID
simulation_ID: 0      

# Max time steps -- total number of iterations
t_max: 1000

# Operation fee for each timestep
operation_fee: 1

# The time to repay loan
# WARNING: must equal to max_payment_delay
loan_repayment_time: 120 

# Annualised bank loan interest rate 
bank_annual_rate: 1.03

# Annualised invoice interest rate
invoice_annual_rate: 1.07 

# Lifespan of a sold invoce
invoice_term: 60

# Moving average window width
window_size: 60 

# Demands generation
demand_generator: normal
distributions:
    normal:
      mean: 50
      sigma: 10
    poisson:
      lambda: 5


# Firm's power (size)
powers: 
    - 1 # Small 
    - 2 # Middle
    - 3 # Large


financing_threshold:
  methods:
    

