---
# Simulation unique ID
sim_id: 0  

# Network topoloy
network_topology: diamond

# Node homogenity 
node_homogenity: True

# Max time steps -- total number of iterations
t_max: 1000

# Whether or not financing is enabled.
financed: True # Having both bank and SC financing 

# Dynamic or zero financing threshold
paradigm: proactive

# Operation fee for each timestep
operation_fee: 1

# The time to repay loan
# WARNING: must equal to max_payment_delay
loan_repayment_time: 120 

# Annualised bank loan interest rate 
bank_annual_rate: 1.03

# Annualised invoice interest rate
invoice_annual_rate: 1.07 

# Lifespan of a sold invoce
invoice_term: 60

# Financing threshold calculation 
moving_average: 
  window_size: 60 

# Firm's power (size)
# Represented them as 1, 2, 3 for computation conveinence
powers: 
  - 1 # Small 
  - 2 # Middle
  - 3 # Large

# Firm power market shares
market_shares: 
  - 1
  - 3
  - 5


### Additional simulation parameters
# Demands generation
demand_generator: normal
distributions:
    normal:
      mean: 50
      sigma: 10
    poisson:
      lambda: 5

    

